name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-publish:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Bootstrap app
      working-directory: ./scripts
      env:
        name: ${{ secrets.NAME }}
        version: ${{ secrets.VERSION }}
        usr: ${{ secrets.USR }}
        psw: ${{ secrets.PSW }}
      run: bash bootstrap.sh 
    - name: Build  app
      env:
        ENVIRONMENT_VARIABLE_NAME: ${{ secrets.NAME }}
        name: ${{ secrets.NAME }}
        version: ${{ secrets.VERSION }}
        usr: ${{ secrets.USR }}
        psw: ${{ secrets.PSW }}
      working-directory: ./scripts
      run: bash build.sh
    - name: Publish  app
      env:
        name: ${{ secrets.NAME }}
        version: ${{ secrets.VERSION }}
        usr: ${{ secrets.USR }}
        psw: ${{ secrets.PSW }}
      working-directory: ./docker
      run: bash publish.sh
