name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Bootstrap app
      run: ./scripts/bootstrap.sh 
    - name: Build  app
      run: bash ./scripts/build.sh {{ secrets.VERSION }}
    - name: Build  app
      run: bash ./docker/publish.sh {{ secrets.NAME }} {{ secrets.VERSION }} {{ secrets.USR }} {{ secrets.PSW }}
